name: asap_py3_env
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - configparser=5.0.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.37
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - numexpr=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.2
  - pcre=8.45
  - pillow=9.3.0
  - pip=22.3.1
  - ply=3.11
  - psutil=5.9.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - pytz=2022.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.8
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - ephem==4.1.3
    - pyephem==9.99
    - pygubu==0.28
    - pypiwin32==223
    - pywin32==305
